language: c
sudo: required
before_install:
  - sudo apt-get install gfortran
script:
  - gfortran -fprofile-arcs -ftest-coverage -O0 hello.f90 -o hello
  - ./hello
  - gcov hello.f90

after_success:
  - pip install --user git+git://github.com/codecov/codecov-python.git@wip && codecov
